export const USER_ONLINE = "USER_ONLINE"
export const LOCATION_UPDATE = "LOCATION_UPDATE"
export const FILE_REQUEST_QUERY = "FILE_REQUEST_QUERY"
export const FILE_REQUEST_ANSWER = "FILE_REQUEST_ANSWER"
